import pygame

#
#   Settings    #

SOUND_MAIN_CHANNEL_VOLUME = 1
SOUND_BG_MUSIC_CHANNEL_VOLUME = 0.3
SOUND_MOVEMENT_CHANNEL_VOLUME = 0.3

HERO_HP = 100
HERO_MONEY = 0
HERO_RUNNING_SPEED = 8
HERO_BASE_SPEED = 4
HERO_SPRITE_SIZE = [19, 31]

# FADE_IN/OUT_SPEED = ...

#
#   Config      #

FIELD_SIZE_X = 5
FIELD_SIZE_Y = 5
TILES_COUNT_X = 40
TILES_COUNT_Y = 20
TILE_WIDTH = 25
TILE_HEIGHT = 25

MAX_TIP_LENGTH = 180

#
# Custom pygame events    #
ON_CHANGE_TILE = pygame.USEREVENT + 1
