FIELD_SIZE_X = 5     # FIELD_X (Разряд тора по x)
FIELD_SIZE_Y = 5     # FIELD_Y (Разряд тора по y)

TILES_COUNT_X = 40   # X
TILES_COUNT_Y = 20   # Y
TILE_WIDTH = TILE_HEIGHT = 25

HERO_HP = 100
HERO_MONEY = 0
HERO_RUNNING_SPEED = 8
HERO_BASE_SPEED = 4
HERO_SPRITE_SIZE = [19, 31]

# TODO
# Game data such as START_HERO_MONEY, HERO_HP...
